In [24]:
import numpy as np

print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.empty((2,5)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[nan  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [29]:
print(np.arange(10, 30,5)) # star开始 end结束 step步进
print(np.arange(5,10,2))

[10 15 20 25]
[5 7 9]
