In [1]:
import numpy as np

print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.empty((2,5)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1.86921143e-306 6.23061763e-307 6.23060065e-307 8.45603441e-307
  9.79111267e-307]
 [1.11260144e-306 1.60219035e-306 8.34448533e-308 1.39071445e-307
  1.33511562e-306]]


In [14]:
print(np.arange(10, 30,5)) # star开始 end结束 step步进
print(np.arange(5,10,2))  
type(np.arange(1,3)) # 返回数组非列表
print(np.arange(6))
print(np.arange(10).reshape(2,5))
print(np.arange(18).reshape(3,6))

[10 15 20 25]
[5 7 9]
[0 1 2 3 4 5]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [35]:
np.random.randint(80,100,size=(3,5)) # 随机生成，80-100整数， 3组5个

array([[84, 97, 95, 85, 99],
       [96, 88, 89, 90, 96],
       [95, 99, 92, 86, 83]])

In [66]:
print(np.random.rand(5))
print(np.random.rand(2,2,3))


[0.15972998 0.62111058 0.66956583 0.26992714 0.01806468]
[[[0.12648468 0.35877817 0.20240723]
  [0.49058006 0.33618811 0.96201713]]

 [[0.65023486 0.65754414 0.62844157]
  [0.32927683 0.72523147 0.14902042]]]


In [68]:
print(np.random.choice([1,3,4,6,0,5,3], size=(3,5))) 

[[3 1 3 0 1]
 [6 1 0 6 0]
 [3 3 0 1 6]]


In [71]:
np.random

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [2]:
import random

random.random() # 生成0-1之间的随机实数

0.6858771754162176

In [3]:
random.uniform(1,3) # 生成1,3之间的随机浮点数

1.6936405331604916

In [4]:
random.randint(1,3) # 生成1,3 之间的随机整数

2

In [21]:
random.randrange(1,25,3) # 生成1,25之间  步进为3 的随机数

4

In [32]:
# random.choice(sequence)，用于从序列中获取一个随机元素。
# 参数sequence表示一个有序类型。sequence在python不是一种特定的类型，而是泛指一系列的类型。list, tuple, 字符串都属于sequence。

import string
random.choice(string.ascii_letters) # 随机选择一个字符串里的元素


'j'

In [42]:
l1 = [1,2,3,4,5]
random.shuffle(l1) # 随机打乱字符串顺序
l1

[4, 5, 2, 1, 3]

In [50]:
# random.sample(sequence, k)，用于从指定序列中随机获取指定长度的切片
random.sample(l1, 2) 

[3, 5]